name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo Bradley-10121981 | docker login -u sergeychn --password-stdin

      - name: Build Docker image
        run: |
          docker build -t sergeychn/dvwa-docker:latest .
      
      - name: Push Docker image
        run: docker push sergeychn/dvwa-docker:latest
