name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "Bradley-10121981" | docker login -u cherevichenkosn@gmail.com --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t cherevichenkosn@gmail.com/dvwa-docker:latest .
          docker push cherevichenkosn@gmail.com/dvwa-docker:latest

